const data = {
  categories: [
    { name: 'Milk teas', image: '/images/milktea.jpg' },
    { name: 'Fruit teas', image: '/images/fruittea.jpg' },
    { name: 'Teas', image: '/images/tea.jpg' },
  ],
  products: [
    {
      category: 'Milk teas',
      name: 'Bubble tea',
      price: 5,
      calorie: 90,
      stock:999,
      image: '/images/bubbletea.jpg',
    },
    {
      category: 'Milk teas',
      name: 'Bubble latte',
      price: 8,
      calorie: 120,
      stock:999,
      image: '/images/bubblelatte.jpg',
    },
    {
      category: 'Milk teas',
      name: 'Bubble taro milk tea',
      price: 6,
      calorie: 430,
      stock:999,
      image: '/images/bubbletaro.jpg',
    },
    {
      category: 'Fruit teas',
      name: 'All fruit tea',
      price: 5.5,
      calorie: 55,
      stock:999,
      image:'/images/allfruit.jpg',
    },
    {
      category: 'Fruit teas',
      name: 'Mango fruit tea',
      price: 1.5,
      calorie: 120,
      stock:999,
      image: '/images/mango.jpg',
    },
    {
      category: 'Fruit teas',
      name: 'Apple tea',
      price: 7,
      calorie: 95,
      stock:999,
      image: '/images/apple.jpg',
    },
    {
      category: 'Teas',
      name: 'Jasmine tea',
      price: 1.9,
      calorie: 18,
      stock:999,
      image: '/images/jasminetea.jpg',
    },
    {
      category: 'Teas',
      name: 'Black tea',
      price: 1.5,
      calorie: 20,
      stock:999,
      image: '/images/blacktea.jpg',
    },
    {
      category: 'Teas',
      name: 'Mint tea',
      price: 3,
      calorie: 50,
      stock:999,
      image: '/images/minttea.jpg',
    },
  ],
};
module.exports = data;
